Script started on Tue Oct 31 19:46:23 2017
warning: could not update utmp entry
blade57(1)% pwd
/courses/cs341/f17/cheungr/hseon/mp2
blade57(2)% ls -lg
total 328
-rwxr-xr-x   1 hseon    cs341-1G    26805 Oct 14 23:18 count.lnx
-rw-r--r--   1 hseon    cs341-1G      152 Oct 14 23:18 count.opc
-rw-r--r--   1 hseon    cs341-1G      327 Oct 14 19:56 count.s
-rw-r--r--   1 hseon    cs341-1G     1757 Oct 14 23:18 count.syms
-rw-r--r--   1 hseon    cs341-1G     2896 Oct 14 23:26 count_ulab.script
-rw-r--r--   1 hseon    cs341-1G     3215 Oct 14 23:47 count_vm.script
-rw-r--r--   1 hseon    cs341-1G      398 Oct 13 23:33 countc.c
-rw-r--r--   1 hseon    cs341-1G     1641 Oct 14 23:18 countc.opc
-rw-r--r--   1 hseon    cs341-1G     2173 Oct 10 15:53 makefile
-rw-r--r--   1 hseon    cs341-1G   147915 Oct 10 15:53 mp2.pdf
-rwxr-xr-x   1 hseon    cs341-1G    26820 Oct 31 19:43 printbin.lnx
-rw-r--r--   1 hseon    cs341-1G      275 Oct 31 19:43 printbin.opc
-rw-r--r--   1 hseon    cs341-1G      815 Oct 31 19:43 printbin.s
-rw-r--r--   1 hseon    cs341-1G     1774 Oct 31 19:43 printbin.syms
-rw-r--r--   1 hseon    cs341-1G      395 Oct 29 14:50 printbinc.c
-rw-r--r--   1 hseon    cs341-1G     1503 Oct 29 14:51 printbinc.opc
-rwxr-xr-x   1 hseon    cs341-1G    17911 Oct 21 12:33 strcpy.lnx
-rw-r--r--   1 hseon    cs341-1G      131 Oct 21 12:15 strcpy.opc
-rw-r--r--   1 hseon    cs341-1G     1541 Oct 21 12:15 strcpy.s
-rw-r--r--   1 hseon    cs341-1G     1346 Oct 21 12:33 strcpy.syms
-rw-r--r--   1 hseon    cs341-1G     5206 Oct 21 13:10 strcpy_ulab.script
-rw-r--r--   1 hseon    cs341-1G     2445 Oct 21 13:07 strcpy_vm.script
-rw-r--r--   1 hseon    cs341-1G      618 Oct 21 12:27 strcpyc.c
-rw-r--r--   1 hseon    cs341-1G     1879 Oct 21 12:33 strcpyc.opc
-rw-r--r--   1 hseon    cs341-1G      426 Oct 10 15:53 sum10.s
-rw-r--r--   1 hseon    cs341-1G     4696 Oct 10 15:53 sum10.script_mod.txt
-rw-r--r--   1 hseon    cs341-1G      159 Oct 10 15:53 sum10c.c
lrwxrwxrwx   1 hseon    cs341-1G       13 Oct 31 19:43 syms -> printbin.syms
-rw-r--r--   1 hseon    cs341-1G        0 Oct 31 19:46 typescript
drwxrwsr-x   2 hseon    cs341-1G     4096 Oct  5 16:10 warmup
blade57(3)% cat printbin.s
.text
.global _printbin
.data
result:
                .ascii "0000 0000\0"

_printbin:
        push    %ebp
        mov             %esp, %ebp
        sub             $8, %esp
        movl    8(%ebp), %eax
        movl    %eax, -4(%ebp)
        movl    $0, -8(%ebp)
        movl    %eax, -8(%ebp)
        shrl    $4, -8(%ebp)
        movl    $result, %edx
        call    donibble
        addl    $1, %edx
        movl    -4(%ebp), %eax
        movl    %eax, -8(%ebp)
        call    donibble
        movl    $result, %eax
        mov             %ebp, %esp
        popl    %ebp
        ret

donibble:
        push    %ebp
        mov             %esp, %ebp
        sub             $16, %esp
        movl    8(%ebp), %eax
        xor             %eax, %eax
        movb    %al, -4(%ebp)
        movl    $4, -12(%ebp)
        movl    $3, -16(%ebp)

loop:
        movl    8(%ebp), %eax
        movl    %eax, -8(%ebp)
        movl    -16(%ebp), %ecx
        shrl    %cl, -8(%ebp)
        and             $1, -8(%ebp)
        movzbl  -8(%ebp), %eax
        addb    $0x30, %al
        movb    %al, (%edx)
        addl    $1, %edx
        sub             $1, -16(%ebp)
        sub             $1, -12(%ebp)
        cmpb    $0, -12(%ebp)
        jne             loop
        mov             %ebp, %esp
        popl    %ebp
        ret
blade57(4)% rm pi[K[Kprintbin.lnx
blade57(5)% make A-[K=r[Kprintbin
/groups/ulab/bin/i386-ld -N -Ttext 1000e0 -o printbin.lnx \
        /groups/ulab/pcdev/lib/startup0.opc /groups/ulab/pcdev/lib/startup.opc \
        printbinc.opc printbin.opc /groups/ulab/pcdev/lib/libc.a
rm -f syms;/groups/ulab/bin/i386-nm -n printbin.lnx>printbin.syms;ln -s printbin.syms syms
blade57(7)% exit
script done on Tue Oct 31 19:47:23 2017
