Script started on Sat 21 Oct 2017 12:47:02 PM EDT
]0;tuser@tutor-vserver: ~/cs341/mp2tuser@tutor-vserver:~/cs341/mp2$ exitmtip -f strcpy.lnxscp -r hseon@users.cs.umb.edu:~/cs341/mp2/strcpyy.lnx .[A]0;tuser@tutor-vserver: ~/cs341/mp2tuser@tutor-vserver:~/cs341/mp2$ [29Pmtip -f strcpy.lnx
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cscp -r hseon@users.cs.umb.edu:~/cs341/mp2/strcpyy.lnx .
hseon@users.cs.umb.edu's password: 
strcpy.lnx                                      0%    0     0.0KB/s   --:-- ETAstrcpy.lnx                                    100%   17KB  17.5KB/s   00:00    
]0;tuser@tutor-vserver: ~/cs341/mp2tuser@tutor-vserver:~/cs341/mp2$ scp -r hseon@users.cs.umb.edu:~/cs341/mp2/strcpyy.lnx .[A]0;tuser@tutor-vserver: ~/cs341/mp2tuser@tutor-vserver:~/cs341/mp2$ exit[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cmtip -f strcpy.lnx
For command help, type ~?
For help on args, rerun without args
Code starts at 0x100100
Using board # 1 
Please type <CR> to confirm console setting: 
Setting console dev to COM2Console: colour EGA+ 80x25
COM1 at 0x03f8 (irq = 4) is a 16550A
COM2 at 0x02f8 (irq = 3) is a 16550A

                 Welcome to UMB Tutor for the PC
   UMB Tutor is a 32-bit protected-mode PC debugger/downloader,
       based on Linux, UMB Tutor for m68k, and remote gdb.
UMB Tutor is free software and you are welcome to distribute copies
of it under certain conditions.  There is no warranty for this program.
The copyright and warranty provisions follow the Gnu general public
license, available for view in gdb and elsewhere.  Full sources available.
--bugs, suggestions, questions to eoneil@cs.umb.edu

Exception 3 at EIP=00057a9b: Breakpoint
Tutor> ~downloading strcpy.lnx

.....Done.

Download done, setting EIP to 100100.
Tutor> go 100100
The strcpy function returned the correct pointer value.
The strcpy function copied the data correctly.
The contents of array s are: Hello World

Exception 3 at EIP=00100110: Breakpoint
Tutor> ~q 
Quit handler: 
killing process 1944 Leaving board #1
]0;tuser@tutor-vserver: ~/cs341/mp2tuser@tutor-vserver:~/cs341/mp2$ exit
exit

Script done on Sat 21 Oct 2017 12:48:10 PM EDT
